"""add commitment candidates and commitments

Revision ID: 95eade3b13bc
Revises: d841432db4ef
Create Date: 2026-10-04 20:19:55.776374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95eade3b13bc'
down_revision: Union[str, Sequence[str], None] = 'd841432db4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitment_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('utterance_id', sa.Integer(), nullable=False),
    sa.Column('utterance_sequence', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('due_text', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['utterance_id'], ['utterances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utterance_id')
    )
    op.create_index(op.f('ix_commitment_candidates_conversation_id'), 'commitment_candidates', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_commitment_candidates_status'), 'commitment_candidates', ['status'], unique=False)
    op.create_table('commitments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('utterance_id', sa.Integer(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('due_text', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['commitment_candidates.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['utterance_id'], ['utterances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_index(op.f('ix_commitments_status'), 'commitments', ['status'], unique=False)
    # op.drop_table('recall_fts_content')
    # op.drop_table('recall_fts_docsize')
    # op.drop_table('recall_fts_data')
    # op.drop_table('recall_fts_config')
    # op.drop_table('recall_fts_idx')
    # op.drop_table('recall_fts')
    # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('recall_fts',
#     sa.Column('conversation_id', sa.NullType(), nullable=True),
#     sa.Column('conversation_title', sa.NullType(), nullable=True),
#     sa.Column('sequence_start', sa.NullType(), nullable=True),
#     sa.Column('sequence_end', sa.NullType(), nullable=True),
#     sa.Column('excerpt', sa.NullType(), nullable=True)
#     )
#     op.create_table('recall_fts_idx',
#     sa.Column('segid', sa.NullType(), nullable=False),
#     sa.Column('term', sa.NullType(), nullable=False),
#     sa.Column('pgno', sa.NullType(), nullable=True),
#     sa.PrimaryKeyConstraint('segid', 'term')
#     )
#     op.create_table('recall_fts_config',
#     sa.Column('k', sa.NullType(), nullable=False),
#     sa.Column('v', sa.NullType(), nullable=True),
#     sa.PrimaryKeyConstraint('k')
#     )
#     op.create_table('recall_fts_data',
#     sa.Column('id', sa.INTEGER(), nullable=True),
#     sa.Column('block', sa.BLOB(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('recall_fts_docsize',
#     sa.Column('id', sa.INTEGER(), nullable=True),
#     sa.Column('sz', sa.BLOB(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_table('recall_fts_content',
#     sa.Column('id', sa.INTEGER(), nullable=True),
#     sa.Column('c0', sa.NullType(), nullable=True),
#     sa.Column('c1', sa.NullType(), nullable=True),
#     sa.Column('c2', sa.NullType(), nullable=True),
#     sa.Column('c3', sa.NullType(), nullable=True),
#     sa.Column('c4', sa.NullType(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.drop_index(op.f('ix_commitments_status'), table_name='commitments')
#     op.drop_table('commitments')
#     op.drop_index(op.f('ix_commitment_candidates_status'), table_name='commitment_candidates')
#     op.drop_index(op.f('ix_commitment_candidates_conversation_id'), table_name='commitment_candidates')
#     op.drop_table('commitment_candidates')
#     # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_commitments_status'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_commitment_candidates_status'), table_name='commitment_candidates')
    op.drop_index(op.f('ix_commitment_candidates_conversation_id'), table_name='commitment_candidates')
    op.drop_table('commitment_candidates')